---
# Staging Inventory
# Template for staging environment

all:
  children:
    cluster_nodes:
      hosts:
        staging-node1:
          ansible_host: 192.168.2.101
          ansible_user: admin
        staging-node2:
          ansible_host: 192.168.2.102
          ansible_user: admin
      vars:
        cluster_name: staging_cluster
        ansible_become: true
        ansible_become_method: sudo

  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3
