network:
  ethernets:
    eno5:
      dhcp4: false
      dhcp6: false
    eno6:
      dhcp4: false
      dhcp6: false
    eno7:
      optional: true
      dhcp4: false
      dhcp6: false
    eno8:
      optional: true
      dhcp4: false
      dhcp6: false
    ens1f0np0:
      optional: true
      dhcp4: false
      dhcp6: false
    ens1f1np1:
      optional: true
      dhcp4: false
      dhcp6: false
    ens2f0np0:
      optional: true
      dhcp4: false
      dhcp6: false
    ens2f1np1:
      optional: true
      dhcp4: false
      dhcp6: false
    ens3f0np0:
      optional: true
      dhcp4: false
      dhcp6: false
    ens3f1np1:
      optional: true
      dhcp4: false
      dhcp6: false
  bonds:
    bond-mgmt:
      interfaces:
        - eno7
        - eno8
      parameters:
        mode: active-backup
      addresses: [10.236.146.165/27]
      routes:
        - to: "0.0.0.0/0"
          metric: 50
          via: "10.236.146.161"
      nameservers:
        addresses: [10.221.16.10,10.221.16.11]
        search: [sero.gic.ericsson.se,seli.gic.ericsson.se,gic.ericsson.se,ericsson.se]
    bond-pfx:
      interfaces:
        - eno5
        - eno6
      parameters:
        mode: 802.3ad
    bond-int:
      addresses: [192.168.0.2/30]
      interfaces:
        - ens2f0np0
        - ens2f1np1
      parameters:
        mode: 802.3ad
    bond-fabric:
      interfaces:
        - ens1f0np0
        - ens1f1np1
      parameters:
        mode: 802.3ad
    bond-gic:
      interfaces:
        - ens3f0np0
        - ens3f1np1
      parameters:
        mode: 802.3ad
  vlans:
    bond-pfx.4:
      link: bond-pfx 
      id: 4
    bond-gic.101:
      link: bond-gic 
      id: 101
    bond-gic.102:
      link: bond-gic
      id: 102
    bond-gic.125:
      link: bond-gic
      id: 125
    bond-pfx.2:
      link: bond-pfx
      id: 2
    bond-pfx.3:
      link: bond-pfx
      id: 3
    bond-pfx.10:
      link: bond-pfx
      id: 10
  bridges:
    br-pfx4:
      addresses: [ 10.237.176.5/29 ]
      interfaces: [ bond-pfx.4 ]
      routes:
        - table: 4
          to: "0.0.0.0/0"
          via: "10.237.176.1"
      routing-policy:
        - table: 4
          to: "10.237.176.0/29"
        - table: 4
          from: "10.237.176.0/29"
    br-gic101:
      addresses: [ 10.236.148.197/27 ]
      interfaces: [ bond-gic.101 ]
      routes:
        - table: 101
          to: "0.0.0.0/0"
          via: "10.236.148.193"
      routing-policy:
      - table: 101
        from: "10.236.148.192/27"
    br-gic102:
      addresses: [ 10.236.148.229/27 ]
      interfaces: [ bond-gic.102 ]
      routes:
        - table: 102
          to: "0.0.0.0/0"
          via: "10.236.148.225"
      routing-policy:
      - table: 102
        from: "10.236.148.224/27"
      - table: 102
        to: "150.132.5.70/32"
    br-gic125:
      addresses: [ 100.79.23.165/28 ]
      interfaces: [ bond-gic.125 ]
      routes:
        - table: 125
          to: "0.0.0.0/0"
          via: "100.79.23.161"
      routing-policy:
      - table: 125
        from: "100.79.23.160/27"
    br-pfx2:
      addresses: [ 21.0.16.5/26 ]
      interfaces: [ bond-pfx.2 ]
      routes:
        - table: 2
          to: "0.0.0.0/0"
          via: "21.0.16.1"
      routing-policy:
      - table: 2
        from: "21.0.16.0/26"
    br-pfx3:
      addresses: [ 21.0.16.69/26 ]
      interfaces: [ bond-pfx.3 ]
      routes:
        - table: 3
          to: "0.0.0.0/0"
          via: "21.0.16.65"
      routing-policy:
      - table: 3
        from: "21.0.16.64/26"
    br-pfx10:
      addresses: [ 10.9.110.137/26 ]
      interfaces: [ bond-pfx.10 ]
      routes:
        - table: 10
          to: "0.0.0.0/0"
          via: "10.9.110.129"
      routing-policy:
      - table: 10
        from: "10.9.110.128/26"
  version: 2
