---
# Meta information for cluster_monitoring role

galaxy_info:
  role_name: cluster_monitoring
  author: FlexiCluster Team
  description: Monitoring and metrics collection for FlexiCluster
  company: Ericsson
  license: MIT-0
  min_ansible_version: "2.7"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
  galaxy_tags:
    - cluster
    - monitoring
    - metrics
    - prometheus
    - sysstat

dependencies:
  - role: cluster_base
